### PR TITLE
#114/add crash logging

### LINKED ISSUE #114: Add voluntary bug reporting to application
If an unhandled error occurs, a dialog / window is presented to the user that contains important information about the error. This allows the user to:
* Send information by mail
* or not send anything.

### PR DESCRIPTION
**Pull request by timosturm**
Closes #114. If an exception occurs anywhere in the app, a screen is presented to the user that contains all information that can be send to the developers.The information is send via mail.

Screenshot_20210225_135443_it netknights piauthenticator

Currently a dummy exception can be triggered by pressing the '+' button in the lower right corner (i.e. scanning qr-codes).

TODOs before this can be merged:
+ [x] @cornelinux Set correct receiver e-mail address (where should the error be messaged to)
+ [ ] @cornelinux A disclaimer may be needed about how the information is processed (because we know the senders e-mail address)
+ [x] Remove dummy exception
+ [x] @nilsbehlen Decide on application version, currently this is planed as a minor release: 3.0.12 -> 3.1.0
+ [x] @nilsbehlen Should the custom error display of the migration be completely removed and replaced by this?

### CODE REVIEW

**Comment by cornelinux** [comment]
In regards to the recipient email address:

Could we add an email address to the QR code? And thus let the operator of privacyIDEA decide, where the message should be sent?
If several tokens provide an email-Address, then the email could be prepared to a list of these email addresses.
Duplicate email addresses should appear only one. @timosturm is this possible?

**Comment by timosturm** [comment]
@cornelinux It is possible, everything is prepared so when this functionality is implemented on the server it can be easily added to the application.

**Comment by nilsbehlen** [comment]
I think we should put this and the device lock (#102) in version 3.1.0.
The catching of errors while migrating should be replaced by this, since it was only a workaround.

**Review by nilsbehlen — APPROVED** [review]

File: lib/screens/main_screen.dart [hunk 1]
```diff
@@ -759,6 +767,7 @@ class _MainScreenState extends State<MainScreen> {
                 builder: (context) => CustomLicenseScreen(),
               ),
             );
+//            throw Exception('Oh no! Something happened.');
```
Comment (timosturm) [inline lib/screens/main_screen.dart:770]:
```suggestion
```
